// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAawOvKsHwBHHc_FhoofahQUP3UHxPs-EU',
    appId: '1:840925341590:web:43075dac1be168f1a31fb7',
    messagingSenderId: '840925341590',
    projectId: 'lastlab-d3e87',
    authDomain: 'lastlab-d3e87.firebaseapp.com',
    storageBucket: 'lastlab-d3e87.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiJqZ3G7zcD_6UKzhUhDwfYUmSMa08qiw',
    appId: '1:840925341590:android:e9e2a78b5f999ae4a31fb7',
    messagingSenderId: '840925341590',
    projectId: 'lastlab-d3e87',
    storageBucket: 'lastlab-d3e87.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3XMW0iSjbTl-hkbb2YlKDrMuyei6NzxU',
    appId: '1:840925341590:ios:a8bf8842b4311dfea31fb7',
    messagingSenderId: '840925341590',
    projectId: 'lastlab-d3e87',
    storageBucket: 'lastlab-d3e87.firebasestorage.app',
    androidClientId: '840925341590-tfhosfujp3qpkvsfj25uicgrm8eh39h7.apps.googleusercontent.com',
    iosClientId: '840925341590-sidr1a1brubp8idrqc79q05aojagmjn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
